#!/bin/bash
#
# Updates projects' CMakeProjectFiles.txt
#

update()
{(
	set -e

	project_path="$1"
	project_name="$2"

	cd "$project_path"

	(
		echo "set(${project_name}_SOURCES"
			find -name '*.cpp' | sed 's/^\.\//\t/'
		echo ')'
		echo ''
		echo "set(${project_name}_MOC_SOURCES"
			for file in $(find -name '*.hpp')
			do
				if grep -F Q_OBJECT "$file" > /dev/null
				then
					echo "$file"
				fi
			done | sed 's/^\.\//\t/'
		echo ')'
		echo ''
		echo "set(${project_name}_UIS"
			find -name '*.ui' | sed 's/^\.\//\t/'
		echo ')'
	) > "CMakeProjectFiles.txt"
)}

update mlib MLIB
update src GROV

